/// Flutter icons SpaSalon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SpaSalon
///      fonts:
///       - asset: fonts/SpaSalon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SpaSalon {
  SpaSalon._();

  static const _kFontFam = 'SpaSalon';
  static const String? _kFontPkg = null;

  static const IconData spa_face_mask = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spa_products = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
